### ISSUE TITLE
realpath() of ../docker/gmission_by_uwsgi/uwsgi.ini failed: No such file or directory [core/utils.c line 3616]

### ISSUE THREAD

**Issue by Hoomaaan** [gmission/gmission#1]
Hello, I installed all the required software mentioned in the gmission's documentation. However, when I perform "docker-compose up" in the gmission/docker directory I face the following error.

![Capture](https://user-images.githubusercontent.com/33916130/64195854-14983f80-ce48-11e9-93dc-15b7db72edc8.JPG)

**Comment by freeznet** [comment]
should caused by docker volume with config error. 
https://github.com/gmission/gmission/blob/remaster/docker/docker-compose.yml

each service in `docker-compose.yml` have 
```
volumes:
    - ../:/GMission-Server
```
and the relative path `../` should be replaced to absolute path.

if your gmission repo placed at `/home/gmission/gmission` then you have to change all `- ../:/GMission-Server` to `- /home/gmission/gmission:/GMission-Server`

also, `docker-compose.yml` is with [docker-compose v1 format](https://docs.docker.com/compose/compose-file/compose-file-v1/), i am not sure if the latest docker-compose can support it or not, PR are welcome.

**Comment by Hoomaaan** [comment]
Thanks for your reply, I changed the volumes directory to the absolute path as you mentioned. However, I still face the same error. 

I also installed docker toolbox and gave it a try again but the error persisted.

**Comment by freeznet** [comment]
if you are using docker with Windows, then you should make sure that gmission repo is cloned or shared into your docker's host VM. 
ref: [https://docs.docker.com/docker-for-windows/#shared-drives](https://docs.docker.com/docker-for-windows/#shared-drives)

**Comment by chenzhao** [comment]
> if you are using docker with Windows, then you should make sure that gmission repo is cloned or shared into your docker's host VM.
> ref: https://docs.docker.com/docker-for-windows/#shared-drives

洛阳铲！
